default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: g2-midterm-assessment_development

test:
  <<: *default
  database: g2-midterm-assessment_test
